import mod_data
import gungeon_error
import std/strformat
import std/sequtils
import std/strutils
import std/algorithm
import std/tables
import std/sets
import utils

import config

# class designating data extracted from a single processed log
type
  ProcessedLog* = ref object
    gungeonVersion* : string # version of gungeon the log was generated with
    bepinexVersion* : string # version of BepInEx the log was generated with
    os* : string # the OS the log was generated with
    platformInterface* : string # the platform interface the log was generated with (Steam, Generic, etc.)
    foundMTGAPIPatcher* : bool # whether MTGAPIPatcher was found
    foundOldMTG* : bool # whether the log was generated by the old MTG Loader
    patchedDll* : bool # whether the game's Assembly-CSharp.dll has been evidently patched
    timestamp* : string # timestamp of the log
    contentsHash* : string # the hash of the raw file contents
    modList* : seq[ModData] # list of mods found in the log
    errorList* : seq[GungeonError] # list of errors found in the log
    totalErrorCount* : int # total count of errors found in log
    uniqueErrors* : OrderedTable[string, GungeonError] # table of unique errors, by hash
    modsWithStartupErrors* : HashSet[string] # mods that have startup errors
    modsWithRuntimeErrors* : HashSet[string] # mods that have runtime errors

proc summarize*(plog : ProcessedLog) : void =
  echo fmt"""Error List:"""
  for e in plog.errorList:
    let phase : string = fmt"""{$(e.errorPhase):<10}"""
    let count : string = fmt"""{$(e.count):>8}"""
    let hash  : string = e.contentHash
    let etype : string = e.errorType
    let emod  : string = if e.errorMod.len() > 0: ("from " & e.errorMod) else : ""
    if e.errorPhase != ErrorPhase.shutdown:
      echo fmt"""  {phase.inGreen()}{(count & " times").inYellow()} {hash.inBlack()} {etype.inCyan()} {emod.inYellow()}"""
      echo e.contents.formatGungeonError(indent = 8)
    else:
      echo fmt"""  {phase}{count} times {hash} {etype} {emod}""".inBlack()

  let modList : seq[ModData] = plog.modList.toSeq().sortedByIt(it.name)
  let modNameLength : int = 2 + modList.mapIt(it.name.len()).foldl(max(a, b))
  let modNamespaceLength : int = 4 + modList.mapIt(modToNamespace.getOrDefault(it.name, "").len()).foldl(max(a, b))
  echo fmt"""Mods Loaded:"""
  for m in modList:
    let s : string = fmt"""  {m.version:>10} {m.name.alignLeft(modNameLength)}"""
    let namespace : string = ("[" & modToNamespace.getOrDefault(m.name, if m.known: "unknown namespace" else: " [unknown mod]") & "]").alignLeft(modNamespaceLength)
    var ss : string

    # determine error state of mod
    if m.name in plog.modsWithStartupErrors:
      ss = s.inRed()
    elif m.name in plog.modsWithRuntimeErrors:
      ss = s.inYellow()
    elif not m.known:
      ss = s.inMagenta()
    else:
      ss = s

    # determine known state of mod
    if m.known:
      ss &= namespace.inBlack()
    else:
      ss &= namespace.inMagenta()

    # fetch tags for mod
    ss &= m.tags.join(", ")
    echo ss

  echo fmt"""-----------"""
  echo fmt"""Log Date:           {plog.timestamp}"""
  echo fmt"""Log Hash:           {plog.contentsHash}"""
  echo fmt"""Operating System:   {plog.os}"""
  echo fmt"""Gungeon Version:    {plog.gungeonVersion.goodIfMatches("2.1.9")}"""
  echo fmt"""BepInEx Version:    {plog.bepinexVersion.goodIfVersionAtLeast("5.4.21.0")}"""
  echo fmt"""Platform Interface: {(plog.platformInterface.goodIfMatchesElseNeutral("Steam"))}"""
  echo fmt"""MTG API Patcher:    {(plog.foundMTGAPIPatcher.goodIfFound())}"""
  echo fmt"""MTG Classic:        {(plog.foundOldMTG.badIfFound())}"""
  echo fmt"""Modified DLL:       {(plog.patchedDll.badIfYes())}"""
  echo fmt"""Mods Installed:     {plog.modList.len()}"""
  echo fmt"""Total Errors:       {plog.totalErrorCount}"""
  echo fmt"""Unique Errors:      {plog.errorList.len()}"""
